schedule Telegram failure messages at 13UTC and 23UTC

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -1,10 +1,12 @@
-name: Node.js CI
+name: Unit Tests
 
 on:
   push:
     branches: [main]
   pull_request:
     branches: [main]
+  schedule:
+    - cron: '0 13,23 * * *'
 
 jobs:
   unit-tests:
@@ -19,14 +21,18 @@ jobs:
         uses: borales/actions-yarn@v4
         with:
           cmd: install
-      - run: yarn test
+      - name: Yarn test up to 3 times
+        shell: bash
+        run: # Try yarn test 3 times before failing
+          r=3;while ! yarn test ; do ((--r))||exit;sleep 1;done
 
   fail-report:
-    if: ${{ failure() }}
+    if: ${{ failure() && github.event_name == 'schedule' }}
     needs: unit-tests
     runs-on: ubuntu-latest
-
     steps:
+      - name: Get repository name
+        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
       - name: Send Telegram message with fail report
         uses: appleboy/telegram-action@master
         with:
@@ -34,5 +40,5 @@ jobs:
           token: ${{ secrets.CI_TELEGRAM_TOKEN }}
           format: markdown
           message: |
-            ❌ **${{ github.repository }}** - Workflow: ${{ github.workflow }}
-            [Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for commit "[${{ github.event.commits[0].message }}](https://github.com/${{ github.repository }}/commit/${{github.sha}})" (${{github.actor}})
+            ❌ **${{ env.REPOSITORY_NAME }}**
+            [${{ github.workflow }} failed](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for commit "[${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{github.sha}})" (${{github.actor}})
